[package]
name = "dnsrelay"
version = "0.1.0"
authors = ["Dan Ho <igaryhe@gmail.com>"]
edition = "2018"

[dependencies]
ron = "*"
failure = "*"
serde = "*"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
